name: Code Checks

on: [push]

defaults:
  run:
    shell: bash

jobs:
  makechecks:
    name: Make Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install yamllint==1.33.0

      - run: |
          make manifests
          make generate
          make fmt
          make vet
          yamllint .
          git diff --exit-code

  # A separate job so that it can annotate the code
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          # Automatically uses ./.golangci.yml for configuration

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - run: |
          make test
          grep -v 'zz_generated.deepcopy.go' raw-cover.out > cover.out

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: cover.out
          output-dir: ${{ github.ref_name }}
          report: true
          chart: false
          amend: false
        if: ${{ github.event_name == 'push' }}
        continue-on-error: true
